### ISSUE TITLE
Would you please share the dataset or at least the data format specifications?

### ISSUE THREAD

**Issue by withchencheng** [ChengYuHsieh/Nemo#1]
Would you please share the dataset or at least the data format specifications? Thank you!

**Comment by ChengYuHsieh** [comment]
Thanks. I just added instructions to download the datasets in `README.md`. Please let me know if there's any problem downloading the datasets.

**Comment by withchencheng** [comment]
Thanks for your quick reply! Can you also share the Visual Genome dataset used in your paper? I didn't find the Visual Genome dataset in your shared google drive link.
