### ISSUE TITLE
ModuleNotFoundError: No module named 'kliep'

### ISSUE THREAD

**Issue by withchencheng** [ChengYuHsieh/Nemo#2]
What is the package 'kliep' in `interactive_dp.py`? You didn't specify in the `requirements.txt`

**Comment by withchencheng** [comment]
I found many online open-source versions of  'kliep'. But I don't know which is the right one you used here.

**Comment by ChengYuHsieh** [comment]
Just updated the instructions to set up the environment. Please let me know if there's further issues. I'll close this issue for now. Thanks.
